export const types = {
  login: "[Auth] Login",
  logout: "[Auth] LogOut",
  authCheking: "[Auth] Checking Login State",
  authChekingFinish: "[Auth] Checking Login State Finish",
  authStartRegister: "[Auth] Start Register",
  authStartTokenRenew: "[Auth] Token renew",
  uiOpenModal: "[UI] Open Modal",
  uiCloseModal: "[UI] Close Modal",
  eventAddNew: "[Events] Add new event",
  eventDelete: "[Events] Delete event",
  eventUpdate: "[Events] Update event",
  eventSetActive: "[Events] Set active event",
  eventDeleteActive: "[Events] Delete active event",
};
